---
#
# Ansible managed
#
repository:
  description: Create encrypted devices using luks and open them at boot.
  homepage: https://robertdebock.nl/
  topics: luks, crypto, ansible, molecule, tox, playbook, hacktoberfest
