---

- name: Test if luks_default_state is set correctly
  ansible.builtin.assert:
    that:
      - luks_default_state is defined
      - luks_default_state is string
      - luks_default_state in [ "absent", "closed", "opened", "present" ]
    quiet: yes

- name: Test if luks_devices is set correctly
  ansible.builtin.assert:
    that:
      - luks_devices is iterable
    quiet: yes
  when:
    - luks_devices is defined

- name: Test if item.name in luks_devices is set correctly
  ansible.builtin.assert:
    that:
      - item.name is defined
      - item.name is string
    quiet: yes
  loop: "{{ luks_devices }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - luks_devices is defined

- name: Test if item.device in luks_devices is set correctly
  ansible.builtin.assert:
    that:
      - item.device is defined
      - item.device is string
    quiet: yes
  loop: "{{ luks_devices }}"
  loop_control:
    label: "{{ item.device }}"
  when:
    - luks_devices is defined

- name: Test if item.state in luks_devices is set correctly
  ansible.builtin.assert:
    that:
      - item.state in [ "absent", "present" ]
    quiet: yes
  loop: "{{ luks_devices }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - luks_devices is defined
    - item.state is defined

- name: Test if item.passphrase in luks_devices is set correctly
  ansible.builtin.assert:
    that:
      - item.passphrase is string
    quiet: yes
  loop: "{{ luks_devices }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - luks_devices is defined
    - item.passphrase is defined

- name: Test if item.keyfile in luks_devices is set correctly
  ansible.builtin.assert:
    that:
      - item.keyfile is string
    quiet: yes
  loop: "{{ luks_devices }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - luks_devices is defined
    - item.keyfile is defined

- name: Test if either keyfile or passphrase is used
  ansible.builtin.assert:
    that:
      - item.passphrase is not defined
    quiet: yes
  loop: "{{ luks_devices }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - luks_devices is defined
    - item.keyfile is defined

- name: Test if either passphrase or keyfile is used
  ansible.builtin.assert:
    that:
      - item.keyfile is not defined
    quiet: yes
  loop: "{{ luks_devices }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - luks_devices is defined
    - item.passphrase is defined

- name: Test if either passphrase or keyfile are set
  ansible.builtin.assert:
    that:
      - item.keyfile is defined or
        item.passphrase is defined
    quiet: yes
  loop: "{{ luks_devices }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - luks_devices is defined
