---
# tasks file for luks

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install requirements
  package:
    name: "{{ luks_requirements }}"
    state: present

- name: manage luks device
  community.crypto.luks_device:
    name: "{{ item.name }}"
    device: "{{ item.device }}"
    state: "{{ item.state | default(luks_default_state) }}"
    passphrase: "{{ item.passphrase | default(omit) }}"
  no_log: true
  loop: "{{ luks_devices }}"
  loop_control:
    label: "{{ item.device }}"
  when:
    - luks_devices is defined

- name: add the luks device to crypttab
  community.general.crypttab:
    name: "{{ item.name }}"
    state: present
    password: "{{ item.passphrase | default(omit) }}"
    backing_device: "{{ item.device }}"
  no_log: yes
  loop: "{{ luks_devices }}"
  loop_control:
    label: "{{ item.device }}"
  when:
    - luks_devices is defined
