---
# tasks file for luks

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install requirements
  package:
    name: "{{ luks_requirements }}"
    state: present

- name: place keyfile
  copy:
    path: "{{ item.keyfile.path }}"
    content: "{{ item.keyfile.path }}"
  loop: "{{ luks_devices }}"
  when:
    - item.keyfile is defined

- name: manage luks device
  community.crypto.luks_device:
    name: "{{ item.name }}"
    device: "{{ item.device }}"
    state: "{{ item.state | default(luks_default_state) }}"
    keyfile: "{{ item.keyfile.path | default(omit) }}"
    passphrase: "{{ item.passphrase | default(omit) }}"
  loop: "{{ luks_devices }}"
  loop_control:
    label: "{{ item.device }}"
  when:
    - luks_devices is defined
