---
- name: prepare
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap

  tasks:
    - name: place keyfile
      copy:
        content: "C0mpl3x1t7"
        dest: /etc/luks_keyfile
        owner: root
        group: root
        mode: "0400"

    - name: make disk.img
      command: dd if=/dev/zero of=/disk.img bs=1M count=100
      args:
        creates: /disk.img

    - name: make /dev/loop0
      command: mknod -m 0660 /dev/loop0 b 7 8
      args:
        creates: /dev/loop0

    - name: losetup -P /dev/loop0 /disk.img
      command: losetup -P /dev/loop0 /disk.img
      args:
        creates: nothing
      failed_when: no

    - name: losetup -d /dev/loop0
      command: lsosetup -d /dev/loop0
      args:
        creates: nothing
      failed_when: no

    - name: losetup -P /dev/loop0 /disk.img
      command: losetup -P /dev/loop0 /disk.img
      args:
        creates: nothing
      failed_when: no
