---
- name: prepare
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap

  tasks:
    - name: place luks_keyfile
      copy:
        content: "C0mpl3x1t7"
        dest: /etc/luks_keyfile
        owner: root
        group: root
        mode: "0400"

    - name: create disk0.img
      command: dd if=/dev/zero of=/disk0.img bs=1M count=100
      args:
        creates: /disk0.img

    - name: create disk1.img
      command: dd if=/dev/zero of=/disk1.img bs=1M count=100
      args:
        creates: /disk1.img

    - name: create /dev/loop0
      command: mknod /dev/loop0 b 7 8
      args:
        creates: /dev/loop0
      notify:
        - link disk0.img to /dev/loop0

    - name: create /dev/loop1
      command: mknod /dev/loop1 b 7 8
      args:
        creates: /dev/loop1
      notify:
        - link disk1.img to /dev/loop1

  handlers:
    - name: link disk0.img to /dev/loop0
      command: losetup /dev/loop0 /disk0.img

    - name: link disk1.img to /dev/loop1
      command: losetup /dev/loop1 /disk1.img
