---
- name: prepare
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap

  tasks:
    - name: create disk0.img
      command: dd if=/dev/zero of=/disk0.img bs=1M count=100
      args:
        creates: /disk0.img

    - name: create /dev/loop0
      command: mknod /dev/loop0 b 7 8
      args:
        creates: /dev/loop0
      notify:
        - link disk0.img to /dev/loop0

  handlers:
    - name: link disk0.img to /dev/loop0
      command: losetup /dev/loop0 /disk0.img
