---
- name: prepare
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap

  tasks:
    - name: place luks_keyfile
      copy:
        content: "C0mpl3x1t7"
        dest: /etc/luks_keyfile
        owner: root
        group: root
        mode: "0400"

    - name: create disk.img
      command: dd if=/dev/zero of=/disk.img bs=1M count=100
      args:
        creates: /disk.img

    - name: create /dev/loop0
      command: mknod /dev/loop0 b 7 8
      args:
        creates: /dev/loop0
      notify:
        - link disk.img to /dev/loop0

  handlers:
    - name: link disk.img to /dev/loop0
      command: losetup /dev/loop0 /disk.img
